# Generated by Django 4.2.28 on 2026-02-10 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name=' Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name=' Descripción')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name=' Código')),
                ('tipo', models.CharField(choices=[('sanitario', ' Sanitario'), ('griferia', ' Grifería'), ('accesorio', ' Accesorio')], default='sanitario', max_length=20, verbose_name=' Tipo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' Precio')),
                ('stock', models.IntegerField(default=0, verbose_name=' Stock')),
                ('activo', models.BooleanField(default=True, verbose_name=' Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name=' Fecha de creación')),
            ],
            options={
                'verbose_name': ' Producto',
                'verbose_name_plural': ' Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificaciones', models.TextField(blank=True, verbose_name=' Especificaciones')),
                ('instrucciones', models.TextField(blank=True, verbose_name=' Instrucciones de uso')),
                ('garantia', models.IntegerField(default=12, verbose_name=' Meses de garantía')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name=' Categoría')),
                ('productos', models.ManyToManyField(blank=True, related_name='categorias', to='products.product', verbose_name=' Productos')),
            ],
            options={
                'verbose_name': ' Categoría de Producto',
                'verbose_name_plural': ' Categorías de Productos',
            },
        ),
    ]
