# Generated by Django 5.2.11 on 2026-02-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_es_encargado_client_usuario'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible_para_clientes',
            field=models.ManyToManyField(blank=True, to='clients.client', verbose_name=' Visible para clientes'),
        ),
    ]
