# Generated by Django 4.2.28 on 2026-02-10 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name=' Número')),
                ('fecha', models.DateField(verbose_name=' Fecha')),
                ('vencimiento', models.DateField(verbose_name=' Vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=' Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=' IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=' Total')),
                ('estado', models.CharField(choices=[('borrador', ' Borrador'), ('enviada', ' Enviada'), ('pagada', ' Pagada')], default='borrador', max_length=20, verbose_name=' Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name=' Fecha de creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name=' Cliente')),
            ],
            options={
                'verbose_name': ' Factura',
                'verbose_name_plural': ' Facturas',
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name=' Fecha de pago')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name=' Método de pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name=' Referencia')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name=' Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' Precio unitario')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name=' Factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name=' Producto')),
            ],
            options={
                'verbose_name': ' Item de Factura',
                'verbose_name_plural': ' Items de Factura',
            },
        ),
    ]
