# Generated by Django 4.2.28 on 2026-02-10 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name=' Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name=' Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name=' Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name=' Dirección')),
                ('tipo', models.CharField(choices=[('individual', ' Persona'), ('empresa', ' Empresa')], default='individual', max_length=20, verbose_name=' Tipo')),
                ('activo', models.BooleanField(default=True, verbose_name=' Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name=' Fecha de creación')),
            ],
            options={
                'verbose_name': ' Cliente',
                'verbose_name_plural': ' Clientes',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas_internas', models.TextField(blank=True, verbose_name=' Notas internas')),
                ('preferencias', models.TextField(blank=True, verbose_name=' Preferencias')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name=' Fecha de registro')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name=' Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name=' Descripción')),
                ('clientes', models.ManyToManyField(blank=True, related_name='categorias', to='clients.client', verbose_name=' Clientes')),
            ],
            options={
                'verbose_name': ' Categoría de Cliente',
                'verbose_name_plural': ' Categorías de Clientes',
            },
        ),
    ]
